site_name: 'Juji Documentation'
site_description: 'Juji Cognitive AI Assistant (Chatbot) Best Practices, Reference Guide, Tutorials, and Trouble Shooting'
site_url: 'https://juji.io/docs'

#repo_name: 'juji-io/docs'
#repo_url: 'https://github.com/juji-io/docs'

copyright: 'Copyright &copy; 2022 <a href="https://juji.io">Juji, Inc.</a>'

google_analytics:
  - 'UA-113933244-1'
  - 'auto'

theme:
  logo: 'img/juji-logo.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  custom_dir: 'theme/'
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: 'deep orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - def_list
  - admonition
  - footnotes
  - tables
  - meta
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      toc_depth: '3'
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.striphtml:
      strip_attributes: ''

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/juji-io'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/juji_io'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/juji-io/'

nav:
  - Juji Home: https://juji.io
  - Beginners' Guide:
    - Get Started on Juji: index.md
    - Tutorials: tutorial.md
    - AI Chatbot Design Tips: quality-chatbot-design-tips.md
    - More Design Tips: chatbot-design-tips-advanced.md
  - Juji Studio:
    - Introduction: juji-studio.md
    - Chatbot Design: juji-studio/design.md
    - Chatbot Deployment: juji-studio/release.md
    - Chatbot Monitoring: juji-studio/reports.md
  - Juji IDE:
    - Introduction: juji-ide.md
    - Concepts: concept.md
    - Language: reference.md
    - Built-in Dialog Library: topics.md
    - System Functions: function.md
    - User-defined Functions: udf.md
    - Scripting Guide: script.md
    - Config-doc Guide: config-doc.md
    - Custom Topics: custom-topics.md
  - Juji API:
    - Introduction: api.md
    - Juji Psychographic Insights API: psychographic-api.md
    - Juji Cognitive AI Chat API: cognitive-ai-chatbot-api.md
    # - Chat API: chat.md
    # - Data Model: nouns.md
    # - Chat Creation API: client.md
    # - Data API: meta.md
    
  - Get Help:
    - FAQs: faq.md
    - Trouble Shooting: trouble-shooting.md
    - Juji Forum: https://forum.juji.io

  - How to Select an AI Chatbot Platform: how-to-select-ai-chatbot-platform.md

  
    
#      - Question-Asking Chatbots: question-asking-chatbot-design-tips.md
#      - Make Chatbots Helpful: helpful-chatbot-design-tips.md
#      - Add Multimedia Chats: multimedia-chatbot-design-tips.md
#      - Support Complex Q&A: multi-turn-chatbot-design-tips.md
#      - Inject Knowledge into Chatbots: func-api-design-tips.md
    
#    - Juji Studio Reference Guide
